### ISSUE TITLE
Cordinate mismatch 

### ISSUE THREAD

**Issue by Akashbhaskaran** [ninepatch/IndoorMapView#2]
I have a leaflet map and i got the cordinates of the markers .
When i try to plot the same cordinates into indoormapview , the marker gets plotted at a different place .

**Comment by RurioLuca** [comment]
thanks for the tip.
could you explain the problem to me better?

Luca

**Comment by Akashbhaskaran** [comment]
When running the app on different phones with varying resolution, the marker gets plotted at different places .

**Comment by RurioLuca** [comment]
It seems very strange to me, the Markers are not tied to the pixels of the screen.
Are you using the same background with the same resolution?

I will however deepen the problem

**Comment by Akashbhaskaran** [comment]
Yes , ofcourse . The same code is built to run on different phones .
