### ISSUE TITLE
Marker Overlayed

### ISSUE THREAD

**Issue by sajetan** [ninepatch/IndoorMapView#3]
Marker objects are not removed and when I try to add the marker in the same coordinate it will overlay on the previous marker. 
I also tried gathering all marker objects and remove using `indoorMapsView.removeMarker(markerobj)` , but it is not helping. 

Let me know if there is anything I'm possibly missing.

![marker](https://user-images.githubusercontent.com/8026042/35329823-392c8684-0127-11e8-87ce-654daf06c7b5.jpeg)

**Comment by RurioLuca** [comment]
thanks for the report as soon as I have time I will check the problem

**Comment by RurioLuca** [comment]
Hi,
I've updated the sample and put the marker removal.
I checked the method and it works correctly you can try the sample

              
```
 indoorMapsView.removeMarker(marker.getId());
  // OR
  indoorMapsView.removeMarker(marker);
```


Let me know 

Luca
